package exceptionHandelling;

public class ExceptionHandellingDemo1 {

	public static void main(String[] args) {
		
		//when exception occurs in try block we handel it it catch block
		
		try {
			
		

		String str = null;
		
		int str_length = str.length();
		
		System.out.println(str_length);
		
		
		
		 
	}catch(NullPointerException e) {
		
		
		System.out.println("NullPointerException is handelled in catch block");
		
		
		
	}
		
		
	
	}
	

	}
